/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for SysTick */
/* Definition of clock source frequency. */
#define SYSTICK_CLK_FREQ 12000000UL
/* Definition of clock source frequency. */
#define SYSTICK_TICKS 12000000UL
/* SysTick interrupt vector ID (number). */
#define SYSTICK_TIMER_REFERENCE_IRQN SysTick_IRQn
/* SysTick interrupt handler identifier. */
#define SysTick_Handler SysTick_Handler

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
/* Initialization UART0 peripherals */

/* Rx transfer buffer size. */
#define LPUART0_RX_BUFFER_SIZE 1
  /* Rx transfer buffer size. */
#define LPUART0_TX_BUFFER_SIZE 25
  /* LPUART0 interrupt vector ID (number). */
//#define LPUART0_IRQN LPUART0_IRQn


void BOARD_InitPeripherals(void);
extern const lpuart_config_t LPUART0_config;
extern lpuart_handle_t LPUART0_handle;
extern uint8_t LPUART0_rxBuffer[LPUART0_RX_BUFFER_SIZE];
extern lpuart_transfer_t LPUART0_rxTransfer;
extern uint8_t LPUART0_txBuffer[LPUART0_TX_BUFFER_SIZE];
extern lpuart_transfer_t LPUART0_txTransfer;
extern uint32_t state_change_delay;
//extern size_t UART_BUFFER_SIZE;
//extern uint8_t g_rx_buffer[UART_BUFFER];


/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);
extern void UART0_Callback(LPUART_Type *base, lpuart_handle_t *handle, status_t status, void *userData);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
